# Generated by Django 4.2.11 on 2025-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_email_alter_staff_phone_and_more'),
    ]

    operations = [
    ]
