# Generated by Django 4.2.11 on 2025-05-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20250530_1148'),
    ]

    operations = [
    ]
