[phases.setup]
nixPkgs = ['python39', 'gcc']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn wj_professionals.wsgi:application --host 0.0.0.0 --port $PORT'
