[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && gunicorn wj_professionals.wsgi:application --bind 0.0.0.0:$PORT"