# Generated by Django 4.2.11 on 2025-06-01 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-publish_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_newsar_status_e12c4c_idx',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this article should be published'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Automatically set when status changes to published', null=True),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['status', 'publish_date'], name='news_newsar_status_a7dbf2_idx'),
        ),
    ]
