# Generated by Django 4.2.11 on 2025-05-28 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_hours', models.TextField(help_text='e.g., Mon-Fri: 8:00 AM - 6:00 PM')),
                ('services_available', models.JSONField(default=list)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('tax', 'Tax Services'), ('audit', 'Audit Services'), ('consulting', 'Business Consulting'), ('bookkeeping', 'Bookkeeping'), ('quote', 'Request Quote'), ('complaint', 'Complaint'), ('partnership', 'Partnership Opportunity')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Message')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('under_100k', 'Under ₦100,000'), ('100k_500k', '₦100,000 - ₦500,000'), ('500k_1m', '₦500,000 - ₦1,000,000'), ('1m_5m', '₦1,000,000 - ₦5,000,000'), ('over_5m', 'Over ₦5,000,000'), ('discuss', 'Prefer to Discuss')], max_length=50)),
                ('timeline', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1_week', 'Within 1 Week'), ('1_month', 'Within 1 Month'), ('3_months', 'Within 3 Months'), ('flexible', 'Flexible')], max_length=50)),
                ('attachment_1', models.FileField(blank=True, upload_to='contact_docs/')),
                ('attachment_2', models.FileField(blank=True, upload_to='contact_docs/')),
                ('attachment_3', models.FileField(blank=True, upload_to='contact_docs/')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('response_sent', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Internal notes for staff', verbose_name='Internal Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_data_processing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Response')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='contact.contactsubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
