# Generated by Django 4.2.11 on 2025-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Expected delivery timeframe', max_length=100),
        ),
    ]
