# Generated by Django 4.2.11 on 2025-05-29 16:45

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_delivery_time_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='company',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='clients_served',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='company',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='values',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Values'),
        ),
        migrations.AddField(
            model_name='company',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Vision'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.TextField(blank=True),
        ),
    ]
