# Generated by Django 4.2.11 on 2025-05-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
