# Generated by Django 4.2.11 on 2025-06-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Service category this testimonial relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.servicecategory'),
        ),
    ]
