# Generated by Django 4.2.11 on 2025-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
