# Generated by Django 4.2.11 on 2025-05-28 04:10

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('sme', 'Small & Medium Enterprise'), ('corporate', 'Large Corporation'), ('ngo', 'Non-Governmental Organization'), ('government', 'Government Agency')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='clients/')),
                ('banner_image', models.ImageField(blank=True, upload_to='clients/banners/')),
                ('project_title', models.CharField(max_length=300)),
                ('project_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Project Description')),
                ('services_provided', models.JSONField(default=list, help_text='List of services provided')),
                ('project_duration', models.CharField(max_length=100)),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('project_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused')], default='completed', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('key_achievements', models.JSONField(default=list, help_text='List of key achievements')),
                ('challenges_overcome', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Challenges Overcome')),
                ('client_benefits', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Client Benefits')),
                ('testimonial', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Testimonial')),
                ('testimonial_author', models.CharField(blank=True, max_length=200)),
                ('testimonial_position', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-industry', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='portfolio.client')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.industry'),
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Problem Statement')),
                ('client_situation', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Client Situation')),
                ('our_approach', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Our Approach')),
                ('methodology', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Methodology')),
                ('tools_used', models.JSONField(default=list)),
                ('quantitative_results', models.JSONField(default=list, help_text='Measurable outcomes')),
                ('qualitative_results', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Qualitative Results')),
                ('roi_achieved', models.CharField(blank=True, max_length=100)),
                ('lessons_learned', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Lessons Learned')),
                ('future_recommendations', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Future Recommendations')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.client')),
            ],
        ),
    ]
